-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.formapago
(
    formapagoid smallint NOT NULL,
    formapagodesc character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT formapago_pkey PRIMARY KEY (formapagoid)
);

CREATE TABLE IF NOT EXISTS public.movil
(
    movilchasis character varying(100) COLLATE pg_catalog."default" NOT NULL,
    movilchapa character varying(100) COLLATE pg_catalog."default" NOT NULL,
    tipomovilid smallint NOT NULL,
    CONSTRAINT movil_pkey PRIMARY KEY (movilchasis)
);

CREATE TABLE IF NOT EXISTS public.persona
(
    personadoc character varying(20) COLLATE pg_catalog."default" NOT NULL,
    personanombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    personaapellido character varying(100) COLLATE pg_catalog."default" NOT NULL,
    personafecnac date NOT NULL,
    tipopersonaid bigint NOT NULL,
    CONSTRAINT persona_pkey PRIMARY KEY (personadoc)
);

CREATE TABLE IF NOT EXISTS public.tipomovil
(
    tipomovilid smallint NOT NULL,
    tipomovildesc character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tipomovil_pkey PRIMARY KEY (tipomovilid)
);

CREATE TABLE IF NOT EXISTS public.tipopersona
(
    tipopersonaid bigint NOT NULL,
    tipopersonadesc character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tipopersona_pkey PRIMARY KEY (tipopersonaid)
);

CREATE TABLE IF NOT EXISTS public.viaje
(
    viajeid bigint NOT NULL,
    viajeconductor character varying(20) COLLATE pg_catalog."default" NOT NULL,
    viajecliente character varying(20) COLLATE pg_catalog."default" NOT NULL,
    formapagoid smallint NOT NULL,
    movilchasis character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT viaje_pkey PRIMARY KEY (viajeid)
);

ALTER TABLE IF EXISTS public.movil
    ADD CONSTRAINT imovil1 FOREIGN KEY (tipomovilid)
    REFERENCES public.tipomovil (tipomovilid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS imovil1
    ON public.movil(tipomovilid);


ALTER TABLE IF EXISTS public.persona
    ADD CONSTRAINT ipersona1 FOREIGN KEY (tipopersonaid)
    REFERENCES public.tipopersona (tipopersonaid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ipersona1
    ON public.persona(tipopersonaid);


ALTER TABLE IF EXISTS public.viaje
    ADD CONSTRAINT iviaje1 FOREIGN KEY (formapagoid)
    REFERENCES public.formapago (formapagoid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS iviaje1
    ON public.viaje(formapagoid);


ALTER TABLE IF EXISTS public.viaje
    ADD CONSTRAINT iviaje2 FOREIGN KEY (movilchasis)
    REFERENCES public.movil (movilchasis) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS iviaje2
    ON public.viaje(movilchasis);


ALTER TABLE IF EXISTS public.viaje
    ADD CONSTRAINT iviaje3 FOREIGN KEY (viajeconductor)
    REFERENCES public.persona (personadoc) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS iviaje3
    ON public.viaje(viajeconductor);


ALTER TABLE IF EXISTS public.viaje
    ADD CONSTRAINT iviaje4 FOREIGN KEY (viajecliente)
    REFERENCES public.persona (personadoc) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS iviaje4
    ON public.viaje(viajecliente);

END;
--josue